import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const MODULE_LENGTH = 2.5;
const BELT_TILE_LENGTH = 0.5;

const variants = [
  {
    filename: "conveyor.xml",
    model: "conveyor",
    bodyName: "conveyor",
    moduleCount: 1,
  },
  {
    filename: "conveyor-long.xml",
    model: "conveyor_long",
    bodyName: "conveyor_long",
    moduleCount: 2,
  },
];

const formatNumber = (value) => {
  const rounded = Math.round(value * 1e9) / 1e9;
  return Object.is(rounded, -0) ? "0" : String(rounded);
};

const renderVisualModule = (moduleIndex, centerY) => {
  const suffix = `module_${moduleIndex}`;
  const pos = `0 ${formatNumber(centerY)} 0`;
  return `      <!-- Reusable polished 2.5 m visual module. -->
      <geom name="conveyor_visual_0_${suffix}" type="mesh" mesh="conveyor_visual_0"
            pos="${pos}" material="conveyor_frame_mat" group="1"
            contype="0" conaffinity="0" density="0"/>
      <geom name="conveyor_visual_1_${suffix}" type="mesh" mesh="conveyor_visual_1"
            pos="${pos}" material="conveyor_frame_mat" group="1"
            contype="0" conaffinity="0" density="0"/>
      <geom name="conveyor_visual_2_${suffix}" type="mesh" mesh="conveyor_visual_2"
            pos="${pos}" material="conveyor_frame_mat" group="1"
            contype="0" conaffinity="0" density="0"/>
      <geom name="conveyor_visual_3_${suffix}" type="mesh" mesh="conveyor_visual_3"
            pos="${pos}" material="conveyor_frame_mat" group="1"
            contype="0" conaffinity="0" density="0"/>`;
};

const renderBeltVisual = (moduleCount) => `      <!-- One continuous belt skin hides the joins between frame modules. -->
      <geom name="conveyor_belt_visual" type="mesh" mesh="conveyor_belt_visual"
            scale="1 ${formatNumber(moduleCount)} 1" material="conveyor_belt_mat" group="1"
            contype="0" conaffinity="0" density="0"/>`;

const renderBeltSegment = (index, centerY) => `      <body name="conveyor_belt_segment_${index}" pos="0.0179964 ${formatNumber(centerY)} 0.88">
        <joint name="conveyor_belt_segment_${index}_slide" type="slide" axis="0 1 0"
               range="-0.25 0.25" limited="false" damping="0"/>
        <geom name="conveyor_belt_segment_${index}_contact" type="box" size="0.39 0.25 0.0125"
              mass="0.02" group="3" rgba="0 0 0 0" condim="6" friction="1.8 0.08 0.02"
              solimp="0.9 0.98 0.0001" solref="0.002 1"/>
      </body>`;

const renderEquality = (index) =>
  `    <joint name="belt_eq_${index}_${index + 1}" joint1="conveyor_belt_segment_${index}_slide" joint2="conveyor_belt_segment_${index + 1}_slide" polycoef="0 1 0 0 0"/>`;

const renderVariant = ({ model, bodyName, moduleCount }) => {
  const length = moduleCount * MODULE_LENGTH;
  const segmentCount = Math.round(length / BELT_TILE_LENGTH);
  const moduleCenters = Array.from(
    { length: moduleCount },
    (_, index) => -length / 2 + MODULE_LENGTH / 2 + index * MODULE_LENGTH
  );
  const segmentCenters = Array.from(
    { length: segmentCount },
    (_, index) => -length / 2 + BELT_TILE_LENGTH / 2 + index * BELT_TILE_LENGTH
  );

  return `<mujoco model="${model}">
  <!-- Generated by generate.mjs. Edit the generator rather than this file. -->
  <compiler angle="radian" meshdir="meshes"/>
  <option timestep="0.002"/>

  <asset>
    <material name="conveyor_frame_mat" rgba="0.48 0.52 0.58 1" metallic="0.72" roughness="0.28"/>
    <material name="conveyor_belt_mat" rgba="0.035 0.04 0.045 1" metallic="0" roughness="0.88"/>
    <mesh name="conveyor_visual_0" file="visual_0.obj" inertia="shell"/>
    <mesh name="conveyor_visual_1" file="visual_1.obj" inertia="shell"/>
    <mesh name="conveyor_visual_2" file="visual_2.obj" inertia="shell"/>
    <mesh name="conveyor_visual_3" file="visual_3.obj" inertia="shell"/>
    <mesh name="conveyor_belt_visual" file="visual_4.obj" inertia="shell"/>
  </asset>

  <worldbody>
    <body name="${bodyName}" pos="0 0 0">
      <!-- Visual meshes never participate in collision. -->
${moduleCenters.map((centerY, index) => renderVisualModule(index, centerY)).join("\n")}
${renderBeltVisual(moduleCount)}

      <!-- Stable primitive collision scales with the generated conveyor length. -->
      <geom name="conveyor_frame_collision" type="box"
            pos="0.0179964 0 0.3527419" size="0.5205209 ${formatNumber(length / 2)} 0.3527419"
            group="3" rgba="0 0 0 0"/>
      <geom name="conveyor_left_rail_collision" type="box"
            pos="-0.4912142 0 0.7242926" size="0.097543 ${formatNumber(length / 2)} 0.21227"
            group="3" rgba="0 0 0 0"/>
      <geom name="conveyor_right_rail_collision" type="box"
            pos="0.5092106 0 0.8212732" size="0.0795466 ${formatNumber(length / 2)} 0.1152895"
            group="3" rgba="0 0 0 0"/>

      <!-- Synchronized 0.5 m tiles form one continuous moving contact surface. -->
${segmentCenters.map((centerY, index) => renderBeltSegment(index, centerY)).join("\n")}
    </body>
  </worldbody>

  <equality>
${Array.from({ length: segmentCount - 1 }, (_, index) => renderEquality(index)).join("\n")}
  </equality>

  <actuator>
    <velocity name="conveyor_speed" joint="conveyor_belt_segment_0_slide" ctrlrange="-1.5 1.5" kv="20"/>
  </actuator>
</mujoco>
`;
};

const outputDirectory = fileURLToPath(new URL(".", import.meta.url));
for (const variant of variants) {
  writeFileSync(new URL(variant.filename, import.meta.url), renderVariant(variant), "utf8");
  console.log(`Generated ${variant.filename} in ${outputDirectory}`);
}
